-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 17:38:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema economy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema economy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `economy` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `economy` ;

-- -----------------------------------------------------
-- Table `economy`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`account` ;

CREATE TABLE IF NOT EXISTS `economy`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `bank` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`account2person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`account2person` ;

CREATE TABLE IF NOT EXISTS `economy`.`account2person` (
  `account_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`account_id`, `person_id`),
  INDEX `fk_person_account_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_account`
    FOREIGN KEY (`person_id`)
    REFERENCES `economy`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_person`
    FOREIGN KEY (`account_id`)
    REFERENCES `economy`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`allocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`allocation` ;

CREATE TABLE IF NOT EXISTS `economy`.`allocation` (
  `percent` INT NOT NULL,
  PRIMARY KEY (`percent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`bill` ;

CREATE TABLE IF NOT EXISTS `economy`.`bill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `company_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `priority` VARCHAR(20) NOT NULL,
  `frequency` INT NOT NULL,
  `payday` INT NOT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bill_category_idx` (`category` ASC) VISIBLE,
  INDEX `fk_bill_priority_idx` (`priority` ASC) VISIBLE,
  INDEX `fk_bill_frequency_idx` (`frequency` ASC) VISIBLE,
  INDEX `fk_bill_debit_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_bill_company_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_bill_category`
    FOREIGN KEY (`category`)
    REFERENCES `economy`.`category` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_priority`
    FOREIGN KEY (`priority`)
    REFERENCES `economy`.`priority` (`level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_frequency`
    FOREIGN KEY (`frequency`)
    REFERENCES `economy`.`frequency` (`months`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_debit`
    FOREIGN KEY (`account_id`)
    REFERENCES `economy`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `economy`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`bill2person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`bill2person` ;

CREATE TABLE IF NOT EXISTS `economy`.`bill2person` (
  `bill_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `allocation` INT NULL,
  PRIMARY KEY (`bill_id`, `person_id`),
  INDEX `fk_person_bill_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_bill`
    FOREIGN KEY (`person_id`)
    REFERENCES `economy`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_person`
    FOREIGN KEY (`bill_id`)
    REFERENCES `economy`.`bill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`category` ;

CREATE TABLE IF NOT EXISTS `economy`.`category` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`company` ;

CREATE TABLE IF NOT EXISTS `economy`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `customer_id` VARCHAR(45) NULL,
  `giro` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`finance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`finance` ;

CREATE TABLE IF NOT EXISTS `economy`.`finance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bill_id` INT NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  `payments` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_finance_bill_id_idx` (`bill_id` ASC) VISIBLE,
  CONSTRAINT `fk_finance_bill_id`
    FOREIGN KEY (`bill_id`)
    REFERENCES `economy`.`bill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`frequency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`frequency` ;

CREATE TABLE IF NOT EXISTS `economy`.`frequency` (
  `months` INT NOT NULL,
  PRIMARY KEY (`months`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`invoice` ;

CREATE TABLE IF NOT EXISTS `economy`.`invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bill_id` INT NOT NULL,
  `ocr` INT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  `deadline` DATETIME NULL,
  `paid` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_invoice_bill_id_idx` (`bill_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoice_bill_id`
    FOREIGN KEY (`bill_id`)
    REFERENCES `economy`.`bill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`person` ;

CREATE TABLE IF NOT EXISTS `economy`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` TEXT NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`priority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`priority` ;

CREATE TABLE IF NOT EXISTS `economy`.`priority` (
  `level` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`level`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`subscription` ;

CREATE TABLE IF NOT EXISTS `economy`.`subscription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bill_id` INT NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  `expires` DATETIME NULL,
  `reminder` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subscription_bill_id_idx` (`bill_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_bill_id`
    FOREIGN KEY (`bill_id`)
    REFERENCES `economy`.`bill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `economy`.`wage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `economy`.`wage` ;

CREATE TABLE IF NOT EXISTS `economy`.`wage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  `payday` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_wage_person_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_wage_account_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_wage_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `economy`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wage_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `economy`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
